//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Qualifications = new HashSet<Qualification>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int Age { get; set; }
        public string Ethnicity { get; set; }
        public string Job { get; set; }
        public string IdCard { get; set; }
        public string PhoneNumber { get; set; }
        public int ProvinceId { get; set; }
        public string Details { get; set; }
        public int DistrictId { get; set; }
        public int TownId { get; set; }
    
        public virtual Ethnicity Ethnicity1 { get; set; }
        public virtual Job Job1 { get; set; }
        public virtual Province Province { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Qualification> Qualifications { get; set; }
    }
}
