//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DAL
{
    public partial class Qualification
    {
        public Qualification() { }

        public Qualification(int id, string name, DateTime releaseDate, int issuancePlace, DateTime expirationDate, int employeeId) 
        {
            Id = id;
            Name = name;
            ReleaseDate = releaseDate;
            IssuancePlace = issuancePlace;
            ExpirationDate = expirationDate;
            EmployeeId = employeeId;
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public int IssuancePlace { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Province Province { get; set; }
    }
}
