//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Qualifications = new HashSet<Qualification>();
        }
    
        public Employee(EmployeeDto employeeDto)
        {
            Id = employeeDto.Id;
            Name = employeeDto.Name;
            DateOfBirth = employeeDto.DateOfBirth;
            Age = employeeDto.Age;
            EthnicityId = employeeDto.EthnicityId;
            JobId = employeeDto.JobId;
            IdCard = employeeDto.IdCard;
            PhoneNumber = employeeDto.PhoneNumber;
            ProvinceId = employeeDto.ProvinceId;
            DistrictId = employeeDto.DistrictId;
            TownId = employeeDto.TownId;
            Details = employeeDto.Details;
            NumberDegree = employeeDto.NumberDegree;
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int Age { get; set; }
        public Nullable<int> EthnicityId { get; set; }
        public Nullable<int> JobId { get; set; }
        public string IdCard { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> TownId { get; set; }
        public string Details { get; set; }
        public Nullable<int> NumberDegree { get; set; }
    
        public virtual District District { get; set; }
        public virtual Ethnicity Ethnicity { get; set; }
        public virtual Job Job { get; set; }
        public virtual Province Province { get; set; }
        public virtual Town Town { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Qualification> Qualifications { get; set; }
    }
}
